### ISSUE TITLE
Remove unnecessary JSObject wrappers

### ISSUE THREAD

**Issue by Janamou** [Janamou/firebase3-dart#13]
For _simple_ classes.

**Comment by kevmoo** [comment]
Look into:

### Auth
- [x] AuthError
- [x] UserProfile

### Storage
- [x] All of the metadata classes

**Comment by Janamou** [comment]
### App
- [x] FirebaseOptions 3618fe8893095c54214508838a2713e7a0f9171d

**Comment by Janamou** [comment]
For the metadata - the customMetadata property is now a Map and is jsified in other metadata classes.

**Comment by kevmoo** [comment]
I just tried to convert it – and failed.

Looks like you just figured this out. 😄 

It'd be nice if we could auto-convert these. Will talk to Jacobe.
