### ISSUE TITLE
How can I verify the auth token on a backend server with dart? 

### ISSUE THREAD

**Issue by borysn** [Janamou/firebase3-dart#20]
Hey guys,

This may not be the right place, or maybe my understanding is wrong, so feel free to correct me!

When previously using gapi library and oauth2 on the front end, I would receive an auth token, and then I would have a backend server verify the auth token. Previously I did this with js/ts/java, but now I'm going all dart to feel things out.

How can I verify the auth token on a backend server with dart? 

I saw that in a previous firebase api, there was a firebase.auth.verifyIdtoken() function, but it does not exist on this library. Is it missing? Or am I not understanding how this is done?

**Comment by Janamou** [comment]
Hi @borysn this page might help you: https://firebase.google.com/docs/auth/server/verify-id-tokens

This library is only a web client. So you can use it to get the token through:

``` dart
String idToken = await firebase.auth().currentUser.getToken(true);
```

And then:

> Once you have an ID token, you can send that JWT to your backend and validate it using one of the official Firebase server SDKs or using a third-party JWT library if your server is written in a language which Firebase does not natively support.

More about verifying: https://firebase.google.com/docs/auth/server/verify-id-tokens#verify_id_tokens_using_the_firebase_sdk

Hope it helps.

**Comment by Janamou** [comment]
@borysn plus I found out that there are some libraries for jwt for Dart on pub: https://pub.dartlang.org/search?q=jwt

**Comment by borysn** [comment]
@Janamou gotcha! Thank you (:
