### ISSUE TITLE
Query.equalTo() sending invalid key value to JS when omitted in Dart.

### ISSUE THREAD

**Issue by montyr75** [Janamou/firebase3-dart#22]
When trying to do something like this:

`ref.orderByChild("email").equalTo("myname@example.com").once("value");`

an exception is generated:

`EXCEPTION: Error: Query.equalTo failed: second argument was an invalid key: "null".  Firebase keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]").`

The second parameter of `equalTo()` is optional, and if omitted, resolves to `null`. That `null` is sent to Firebase's JS library, producing the error. I have confirmed that if `jsObject.equalTo()` is called without the `null` value for the `key` parameter, everything works as expected.

It's likely that other methods, such as `endAt()`, have the same issue.

**Comment by Janamou** [comment]
Hi @montyr75,
can you pull the library from here? I think this should be fixed already.
Thx for the info.

**Comment by montyr75** [comment]
Yes! I can see in the code here that it has been addressed.  :)
