### ISSUE TITLE
Silent error while setting a complex Dart object

### ISSUE THREAD

**Issue by Tomucha** [Janamou/firebase3-dart#27]
Čusne?

I did this:
database.ref("test").set(game);

I didn't expect it to be working - "game" is pretty complex Dart object, but I was curious what is going to happen. And ... nothing happened. I should see some error in browser console, some "uncaught exception" or so.

(BTW - obviously - no data appeared in FB console).
(P.S. Writing simple values works, in case you are wondering).

Thanks!

**Comment by Janamou** [comment]
@Tomucha It has to be something which we are able to convert to JSON easily - e.g. a Map, Iterable or some primitive type.

I Need to update doc to make it more clear.

**Comment by Janamou** [comment]
@Tomucha so you need to make game a Map, Iterable or primitive type :-D

**Comment by Janamou** [comment]
#28

**Comment by Janamou** [comment]
Issue: #28

**Comment by kevmoo** [comment]
> so you need to make game a Map, Iterable or primitive value :-D

Or just implement `toJson` on it and store it that way.

**Comment by Tomucha** [comment]
The point is - it fails silently, which is bad, m'key? Someday, someone is going to be very confused because of this.

So #28 sounds great, just change "consider" to "implement" :-)

**Comment by Janamou** [comment]
Closed in favor of #28 ;-)
