### ISSUE TITLE
Implement adding checks for Map, Iterable or primitive types for set, update and similar methods

### ISSUE THREAD

**Issue by Janamou** [Janamou/firebase3-dart#28]
In other case, the exception should be thrown.

**Comment by Janamou** [comment]
Implement in methods of classes:
- [x] DatabaseReference
- [x] Query
- [x] OnDisconnect
- [x] StorageReference

**Comment by Janamou** [comment]
More validation needed on:
- [x] methods with priority
- [x] filtering methods

Edit: Firebase handles validation for these methods itself :-)

**Comment by Janamou** [comment]
Priority validation: 8bed08c2af80be090cb6434c24c61dd49b8e4b46

**Comment by Tomucha** [comment]
Kudos!
